#!/usr/bin/env python3
"""Generates src/data/dictionaryEn.ts — the English word list for the game —
from WordNet noun lemmas scored by their Zipf frequency in English according
to rspeer/wordfreq. Mirrors the Russian pipeline (annotate_word_frequency.py)
so both dictionaries share the DictionaryEntry shape and difficulty semantics.

Only reasonably common, single-word nouns are kept, so the cards stay
guessable in a party setting. `levenshtein_zipf_frequency` is set equal to
`frequency` here (the Russian pipeline blends in close spelling neighbours,
but that field carries little weight in the difficulty model — see
utils/shuffle.ts — so the approximation is fine for the English list).

Usage:
    pip install wordfreq nltk
    python3 -c "import nltk; nltk.download('wordnet')"
    python3 scripts/generate_english_dictionary.py
"""
import re
from pathlib import Path

from wordfreq import zipf_frequency
from nltk.corpus import wordnet as wn

OUT_PATH = Path(__file__).resolve().parent.parent / "src" / "data" / "dictionaryEn.ts"
LANG = "en"
MIN_ZIPF = 3.0            # ~12.9k nouns; common enough to be guessable
WORD_RE = re.compile(r"^[a-z]{3,16}$")

# Difficulty tiers by Zipf frequency (higher = more common = easier).
EASY_MIN = 4.0
MEDIUM_MIN = 3.4

# Keep the card deck family-friendly: drop obvious profanity/slurs that clear
# the frequency bar. Not exhaustive, but covers the common offenders.
BLOCKLIST = {
    "sex", "ass", "arse", "shit", "crap", "piss", "dick", "cock", "pussy",
    "bitch", "bastard", "damn", "hell", "fuck", "tit", "boob", "penis",
    "vagina", "anus", "rape", "nigger", "faggot", "whore", "slut", "cunt",
    "semen", "turd", "prick", "wank", "porn", "nazi",
}


VOWELS = set("aeiouy")


def difficulty(zipf: float) -> str:
    if zipf >= EASY_MIN:
        return "easy"
    if zipf >= MEDIUM_MIN:
        return "medium"
    return "hard"


def is_wordy(word: str) -> bool:
    # Reject acronym/noise tokens like "aaa" or "xvi": must have a vowel and
    # at least two distinct letters.
    return any(c in VOWELS for c in word) and len(set(word)) >= 2


def is_common_noun(word: str) -> bool:
    # Keep only lemmas that have at least one *common*-noun sense. Proper-noun
    # lemmas (people, places, brands — e.g. "aaron") have only "instance"
    # synsets and are dropped, since they don't make good party cards.
    synsets = wn.synsets(word, pos="n")
    return bool(synsets) and any(not s.instance_hypernyms() for s in synsets)


def main() -> None:
    lemmas = {
        w
        for w in wn.all_lemma_names(pos="n")
        if WORD_RE.match(w) and w not in BLOCKLIST and is_wordy(w)
    }

    entries = []
    for word in lemmas:
        zipf = zipf_frequency(word, LANG)
        if zipf < MIN_ZIPF or not is_common_noun(word):
            continue
        entries.append((word.capitalize(), round(zipf, 2), difficulty(zipf)))

    entries.sort(key=lambda e: e[0])

    lines = [
        "import type { DictionaryEntry } from './dictionary';",
        "",
        "// Auto-generated by scripts/generate_english_dictionary.py — do not edit by hand.",
        "// English nouns (WordNet) scored by Zipf frequency (rspeer/wordfreq).",
        "export const dictionaryEn: DictionaryEntry[] = [",
    ]
    for word, freq, diff in entries:
        lines.append(
            f'  {{ word: "{word}", difficulty: "{diff}", '
            f"frequency: {freq}, levenshtein_zipf_frequency: {freq} }},"
        )
    lines.append("];")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUT_PATH}")


if __name__ == "__main__":
    main()
